name: litho
version: "1.0"
config-version: 2
profile: litho

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  litho:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
